### ISSUE TITLE
NoMethodError: undefined method `httpdate'

### ISSUE THREAD

**Issue by mamodom** [regalii/regaliator#22]
Hi, I'm having an issue trying to do some initial testing with this library.

```
$ ruby -v; bundler -v; cat Gemfile; echo '# Gemfile.lock'; cat Gemfile.lock; cat main.rb; ruby main.rb
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
Bundler version 1.15.4

# Gemfile
gem 'regaliator', github: 'regalii/regaliator'

# Gemfile.lock
GIT
  remote: git://github.com/regalii/regaliator.git
  revision: 6aa6c5db309265122c0be2ccc12cc9d51e2397d6
  specs:
    regaliator (4.1.0)
      json

GEM
  specs:
    json (2.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  regaliator!

BUNDLED WITH
   1.15.4

# main.rb
require 'regaliator'

Regaliator.configure do |config|
    # Version target
    config.version      = '3.1'

    # Authentication settings
    config.api_key      = ENV['REGALII_API_KEY']
    config.secret_key   = ENV['REGALII_SECRET']

    # API host settings
    config.host         = 'api.casiregalii.com'
    config.open_timeout = 5
    config.read_timeout = 60
    config.use_ssl      = true

    # Proxy settings
    config.proxy_host   = nil
    config.proxy_port   = nil
    config.proxy_user   = nil
    config.proxy_pass   = nil
  end

utilities = Regaliator.biller.utilities

/home/mamodom/.rvm/gems/ruby-2.4.0/gems/regaliator-4.0.1/lib/regaliator/request.rb:17:in `initialize': undefined method `httpdate' for 2017-10-25 01:15:20 UTC:Time (NoMethodError)
        from /home/mamodom/.rvm/gems/ruby-2.4.0/gems/regaliator-4.0.1/lib/regaliator/endpoint.rb:14:in `new'
        from /home/mamodom/.rvm/gems/ruby-2.4.0/gems/regaliator-4.0.1/lib/regaliator/endpoint.rb:14:in `request'
        from /home/mamodom/.rvm/gems/ruby-2.4.0/gems/regaliator-4.0.1/lib/regaliator/v30/biller.rb:15:in `utilities'
        from main.rb:26:in `<main>'
```

**Comment by jdsampayo** [comment]
Hi,

Thanks for reporting your issue.

Please include https://apidock.com/rails/ActiveSupport/TimeWithZone/httpdate in your project.

Have a great day!
